#+title: Musings On Twk

** Goal

The goal of Twk is to have absolute feature parity with datastar.wow except it is built as a [[https://github.com/brianium/sandestin][Sandestin]] library.

** Differences with datastar.wow

=datastar.wow= exposes a registry system. I want Twk to abandon owning the registry and dispatch concept (which is what datastar.wow does), and instead explicitly embrace the Sandestin registry system.
Everything necessary should be in the existing datastar.wow code - including what effects and actions to expose - as well as a full schema. The main `ascolais.twk` namespace should export everything else
from the =datastar.wow= namespace:
- =datastar.wow/with-datastar= this is how a ring app becomes powered by the effect system. It is the main export. I am guessing the dispatch arg becomes required and explicit (takes a sandestin dispatch function)
- The values cloned from the official Datastar Clojure SDK using def-clone

Any references to Nexus should obviously be replaced with references to Sandestin.

** References

- /Users/brian/projects/datastar.wow/  (contains full source for the datastar.wow library)
- /Users/brian/projects/sandestin/ (contains full source of the sandestin library if skills are not adequate)
- /Users/brian/projects/datastar-clojure/ (the official Datastar Clojure SDK)
- /Users/brian/projects/datastar-clojure/libraries/sdk (the core API of the Datastar Clojure SDK - i.e the main Datastar dependency of datastar.wow)

** Permission to improve

The main goal is feature parity with datastar.wow, but if we see an opportunity to improve upon datastar.wow without blowing up the scope - lets do so. Let's make this discussion
collaborative if the situation arises.



